import Link from "next/link";
import Navigation from "./components/Navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <head>
        <title>Mi first app with next 13 ccc</title>
      </head>
      <body>
        <Navigation></Navigation>
        {children}
      </body>
    </html>
  );
}
